//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace UserLimitMVC.Model
{
    public partial class DataModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=DataModelContainer";
        public const string ContainerName = "DataModelContainer";
    
        #region Constructors
    
        public DataModelContainer()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public DataModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public DataModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // 创建代理需要使用 ProxyDataContractResolver 和
            // 可允许延迟加载，这可以在序列化期间展开加载图。
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet 属性
    
        public ObjectSet<BasePermission> BasePermission
        {
            get { return _basePermission  ?? (_basePermission = CreateObjectSet<BasePermission>("BasePermission")); }
        }
        private ObjectSet<BasePermission> _basePermission;
    
        public ObjectSet<BaseRole> BaseRole
        {
            get { return _baseRole  ?? (_baseRole = CreateObjectSet<BaseRole>("BaseRole")); }
        }
        private ObjectSet<BaseRole> _baseRole;
    
        public ObjectSet<BaseUser> BaseUser
        {
            get { return _baseUser  ?? (_baseUser = CreateObjectSet<BaseUser>("BaseUser")); }
        }
        private ObjectSet<BaseUser> _baseUser;
    
        public ObjectSet<R_Role_Permission> R_Role_Permission
        {
            get { return _r_Role_Permission  ?? (_r_Role_Permission = CreateObjectSet<R_Role_Permission>("R_Role_Permission")); }
        }
        private ObjectSet<R_Role_Permission> _r_Role_Permission;
    
        public ObjectSet<R_User_Permission> R_User_Permission
        {
            get { return _r_User_Permission  ?? (_r_User_Permission = CreateObjectSet<R_User_Permission>("R_User_Permission")); }
        }
        private ObjectSet<R_User_Permission> _r_User_Permission;
    
        public ObjectSet<R_User_Role> R_User_Role
        {
            get { return _r_User_Role  ?? (_r_User_Role = CreateObjectSet<R_User_Role>("R_User_Role")); }
        }
        private ObjectSet<R_User_Role> _r_User_Role;

        #endregion
    }
}
